// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16eX048B7ODQFPraK83KQTy2TqyKz0_4',
    appId: '1:449674300954:web:c0ba6e8e98d26041b58ba3',
    messagingSenderId: '449674300954',
    projectId: 'clone-spotify-286f2',
    authDomain: 'clone-spotify-286f2.firebaseapp.com',
    storageBucket: 'clone-spotify-286f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdp66Xiud33UAZxUsW6-KJMrIudgTTmLc',
    appId: '1:449674300954:android:42190dc087597b07b58ba3',
    messagingSenderId: '449674300954',
    projectId: 'clone-spotify-286f2',
    storageBucket: 'clone-spotify-286f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr_owaI28Db50NMY_t_USHCyj9JtU2pqk',
    appId: '1:449674300954:ios:3bb869775b672608b58ba3',
    messagingSenderId: '449674300954',
    projectId: 'clone-spotify-286f2',
    storageBucket: 'clone-spotify-286f2.appspot.com',
    iosBundleId: 'com.example.cloneSpotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr_owaI28Db50NMY_t_USHCyj9JtU2pqk',
    appId: '1:449674300954:ios:3bb869775b672608b58ba3',
    messagingSenderId: '449674300954',
    projectId: 'clone-spotify-286f2',
    storageBucket: 'clone-spotify-286f2.appspot.com',
    iosBundleId: 'com.example.cloneSpotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD16eX048B7ODQFPraK83KQTy2TqyKz0_4',
    appId: '1:449674300954:web:a35989f11dd7061cb58ba3',
    messagingSenderId: '449674300954',
    projectId: 'clone-spotify-286f2',
    authDomain: 'clone-spotify-286f2.firebaseapp.com',
    storageBucket: 'clone-spotify-286f2.appspot.com',
  );
}
